CREATE TABLE IF NOT EXISTS IpoBids (
	id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	userId int(11) UNSIGNED NOT NULL,
	stockId int(11) UNSIGNED NOT NULL,
	slotPrice bigint(11) UNSIGNED NOT NULL,
	slotQuantity bigint(11) UNSIGNED NOT NULL,
	stockQuantityFulFilled bigint(11) UNSIGNED NOT NULL,
	isClosed BOOLEAN NOT NULL DEFAULT FALSE,
	isFulfilled BOOLEAN NOT NULL DEFAULT FALSE,
	createdAt varchar(255) NOT NULL DEFAULT "0000-00-00T00:00:00+05:30",
	updatedAt varchar(255) NOT NULL DEFAULT "0000-00-00T00:00:00+05:30",
	PRIMARY KEY (id),
	FOREIGN KEY (userId) REFERENCES Users(id),
	FOREIGN KEY (stockId) REFERENCES IpoStocks(id)
) AUTO_INCREMENT=1;



	