version: 2
jobs:
  build:
    working_directory: /go/src/github.com/delta/dalal-street-server
    docker:
      - image: circleci/golang:1.16
      - image: circleci/mysql:5.7

    steps:
      - checkout

      - run:
          name: Setup protobuf
          command: |
            curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v3.15.8/protoc-3.15.8-linux-x86_64.zip
            unzip protoc-3.15.8-linux-x86_64.zip
            go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
            go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1

      - run:
          name: Update submodules
          command: |
            git submodule init
            git submodule update --recursive

      - run:
          name: Run protobuf tests
          command: |
            export PATH=$PATH:$(pwd)/bin
            export PATH=$PATH:/go/bin/
            export PATH=$PATH:/usr/local/go/bin
            ./build_proto.sh


      - run:
          name: Setup MySQL
          command: |
            sudo apt-get update
            sudo apt install -y default-mysql-client
            mysql -h 127.0.0.1 -u root -e 'CREATE DATABASE dalalstreet_test;'
      
      - run:
          name: Run unit and integration tests
          command: |
            export PATH=$PATH:/go/bin/
            export PATH=$PATH:/usr/local/go/bin
            go install -tags 'mysql' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
            go get
            cp config.json.example config.json
            ./test.sh
