package models

const SHORT_SELL_BORROW_LIMIT = 50
const BID_LIMIT = 50
const ASK_LIMIT = 50
const BUY_LIMIT = 30
const MINIMUM_CASH_LIMIT = 0
const BUY_FROM_EXCHANGE_LIMIT = 20
const ORDER_PRICE_WINDOW = 20

const STARTING_CASH = 200000

const MORTGAGE_RETRIEVE_RATE = 90
const MORTGAGE_DEPOSIT_RATE = 80

const MARKET_EVENT_COUNT = 10
const MY_ASK_COUNT = 10
const MY_BID_COUNT = 10
const GET_NOTIFICATION_COUNT = 10
const GET_TRANSACTION_COUNT = 10
const LEADERBOARD_COUNT = 10

const MARKET_IS_OPEN_HACKY_NOTIF = "Market is open"
const MARKET_IS_CLOSED_HACKY_NOTIF = "Market is closed"
